// <auto-generated />
using GrpcService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrpcService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220430112713_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GrpcService.Models.Siswa", b =>
                {
                    b.Property<int>("SiswaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiswaId"), 1L, 1);

                    b.Property<string>("NamaBel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaDepan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sekolah")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiswaId");

                    b.ToTable("Siswas");

                    b.HasData(
                        new
                        {
                            SiswaId = 11,
                            NamaBel = "Fox",
                            NamaDepan = "Ann",
                            Sekolah = "Nursing"
                        },
                        new
                        {
                            SiswaId = 22,
                            NamaBel = "Doe",
                            NamaDepan = "Sam",
                            Sekolah = "Mining"
                        },
                        new
                        {
                            SiswaId = 33,
                            NamaBel = "Cox",
                            NamaDepan = "Sue",
                            Sekolah = "Business"
                        },
                        new
                        {
                            SiswaId = 44,
                            NamaBel = "Lee",
                            NamaDepan = "Tim",
                            Sekolah = "Computing"
                        },
                        new
                        {
                            SiswaId = 55,
                            NamaBel = "Ray",
                            NamaDepan = "Jan",
                            Sekolah = "Computing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
